version: 1.2
workflows:
   -  name: Dipcall
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/dipcall.wdl
   -  name: BUSCO
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/busco.wdl
   -  name: Quast
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/quast.wdl
      testParameterFiles:
        - /QC/test/s3_quast.json
   -  name: Meryl
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/meryl.wdl
   -  name: Merqury
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/merqury.wdl
   -  name: Asmgene
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/asmgene.wdl
   -  name: YakAsmStats
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak.wdl
   -  name: YakAsmStatsnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak_no_qv.wdl
   -  name: asmChrCompleteness
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/asm_chr_completeness.wdl
   -  name: Mash
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/mash.wdl
   -  name: NTSM
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/tasks/ntsm.wdl
   -  name: MaskAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/mask_assembly.wdl
   -  name: renameContigsAddMT
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/renameContigsAddMT.wdl
   -  name: finalizeGenbankAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/finalizeGenbankAssembly.wdl
   -  name: findMitoContigs
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/findMitoContigs.wdl
   -  name: ReadStats
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/tasks/read_stats.wdl
      testParameterFiles:
        - /QC/test/s3_read_stats.json
   -  name: FullQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/full_qc.wdl
   -  name: StandardQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc.wdl
   -  name: StandardQCnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_no_qv.wdl
   -  name: StandardQCnonTrio
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_nontrio.wdl    
   -  name: FilterHiFiAdapter
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/filter_hifi_adapter.wdl
   -  name: ExtractMitoContigs
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/extractMitoContigs.wdl
   -  name: dropFastaContigs
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/dropFastaContigs.wdl
   -  name: writeUnmappedReads
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/writeUnmappedReads.wdl
   -  name: fastqReadCounts
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/tasks/fastqReadCounts.wdl
      testParameterFiles:
        - /QC/test/s3_fastqReadCounts.json
   -  name: fastqReadCoverage
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/fastqReadCoverage.wdl
   -  name: TrioHifiasmAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly.wdl
   -  name: TrioHifiasmAssemblyYakInput
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly_yak_input.wdl
   -  name: TrioHifiasmAssemblyYakInputCutadapt
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly_yak_input_cutadapt.wdl
   -  name: TrioHifiasmAssemblyYakInputCutadaptMultiStep
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly_yak_input_cutadapt_multistep.wdl
   -  name: TrioHifiasmAssemblyStep3
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/hifiasm_cutadapt_trio_step3.wdl
   -  name: HiCHifiasmAssemblyStep2
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/hifiasm_cutadapt_hic_step2.wdl
   -  name: HiCHifiasmAssemblyStep3
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/hifiasm_cutadapt_hic_step3.wdl
   -  name: TrioVerkkoAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_verkko_assembly.wdl
   -  name: TrioVerkkoAssemblyScatter
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_verkko_assembly_scatter.wdl
   -  name: VerkkoAssemblyScatter
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/verkko_assembly_scatter.wdl
   -  name: VerkkoCreateUnphasedGFA
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/verkko_create_unphased_gfa.wdl
   -  name: VerkkoConsensusFromGFAse
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/verkko_consensus_from_gfase.wdl
   -  name: VerkkoHiCPhasing
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/verkko_hic.wdl
   -  name: VerkkoExtractPhasedAsms
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/verkko_extract_run_folder.wdl
   -  name: VerkkoRephaseRukki
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/verkko_rerun_rukki.wdl
   -  name: YakNoStats
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/yak_no_stats.wdl
   -  name: YakNoStatsHiFi
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/yak_no_stats_hifi.wdl
   -  name: PhasedGFAs2Fasta
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/gfatools.wdl
   -  name: StandardQCHaploid
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_haploid.wdl
   -  name: Primrose
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/tasks/primrose.wdl
   -  name: Contamination
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/contamination.wdl
   -  name: MinigraphMap
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/minigraph.wdl
   -  name: MisjoinCheck
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/misjoinCheck.wdl
   -  name: snvInDelAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/snv_indel_assembly.wdl
   -  name: svAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/SV_assembly.wdl
   -  name: Guppy
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/workflows/scatterGuppy.wdl
   -  name: BreakIntoContigs
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/break_into_contigs.wdl
   -  name: LengthFilterFasta
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/len_filter_fasta.wdl
   -  name: DownSampling
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/down_sampling.wdl
   -  name: FilterShortReads
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/filter_short_reads.wdl
   -  name: chopperFilter
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/tasks/chopper.wdl
   -  name: LiftOff
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/liftoff.wdl
   -  name: ShortQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/short_qc.wdl
   -  name: asmComparisonQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/comparison_qc.wdl
   -  name: asmComparisonQCdiploid
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/comparison_qc_diploid.wdl
   -  name: s5cmd_download
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/tasks/s5cmd_download.wdl      
   -  name: AssemblyCleanUp
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/assembly_clean_up.wdl
   -  name: ShortDiploidQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/short_diploid_qc.wdl 
   -  name: Readsbam4DC
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/tasks/readsbam4dc.wdl
   -  name: ontSummaryStats
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/tasks/calc_ont_summary_stats.wdl
   -  name: compleasmRun
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/compleasm.wdl
   -  name: hifiQC
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/workflows/hifi_qc_workflow.wdl
   -  name: ontQC
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/workflows/ont_qc_workflow.wdl
   -  name: NucFreq
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/nucfreq.wdl
   -  name: bedToBigBed
      subclass: WDL
      primaryDescriptorPath: /annotation/wdl/tasks/bed_to_bigbed.wdl
   -  name: repeatMasker
      subclass: WDL
      primaryDescriptorPath: /annotation/wdl/workflows/repeat_masker.wdl