[build-system]
requires = [
	"flit_core >=3.2,<4",
	"python_version >= '3.9'"
	]
build-backend = "flit_core.buildapi"

[project.urls]
Home = "https://github.com/human-pangenomics/hpp_production_workflows"

